force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Company__c/fields/Id__c.field-meta.xml
<CustomField>
    <fullName>Id__c</fullName>
    <displayFormat>C-{000}</displayFormat>
    <label>Id</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Company__c/fields/Revenue__c.field-meta.xml
<CustomField>
    <fullName>Revenue__c</fullName>
    <label>Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/UpdateCompany.cls
global class UpdateCompany implements Database.Batchable<sObject> {
    private Integer count=0;
    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([SELECT Id__c,Name,Revenue__c FROM Company__c]);
    }
    
    global void execute(Database.BatchableContext bc,List<Company__c> compList) {
        for(Company__c c: compList) {
            c.Revenue__c=200000;
        }
        update compList;
        count=compList.size();
    }	
    
    global void finish(Database.BatchableContext bc) {
        System.debug('Company Count :'+count);
        Messaging.SingleEmailMessage mail=new Messaging.SingleEmailMessage();
        
        String[] toAddr=new String[]{'saurabh.gund@eternussolutions.com','sjgund9795@gmail.com'};
        mail.setToAddresses(toAddr);
        mail.setSubject('Regarding Annual Revenue');
        mail.setPlainTextBody('Hello'+toAddr+'\nOur anuual revenue is updated. Please check');	
        Messaging.sendEmail(new Messaging.SingleEmailMessage[]{mail});
    }
}