force-app/main/default/objects/A__c/A__c.object-meta.xml
<CustomObject>
    <label>A</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>A</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/B__c/B__c.object-meta.xml
<CustomObject>
    <label>B</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>B</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/C__c/C__c.object-meta.xml
<CustomObject>
    <label>C</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>C</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/C__c/fields/A__c.field-meta.xml
<CustomField>
    <fullName>A__c</fullName>
    <label>A</label>
    <referenceTo>A__c</referenceTo>
    <relationshipLabel>C</relationshipLabel>
    <relationshipName>C</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/C__c/fields/B__c.field-meta.xml
<CustomField>
    <fullName>B__c</fullName>
    <label>B</label>
    <referenceTo>B__c</referenceTo>
    <relationshipLabel>C</relationshipLabel>
    <relationshipName>C</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/RelationshipQuery.cls
public class RelationshipQuery {
    
    public static void displayContact() {
		List<Account> accList = [SELECT AccountNumber, Name FROM Account WHERE Active__c='Yes' AND Industry='Media'];
        for(Account a :accList) {
            List<Contact> conList = [SELECT Name, Account.Name From Contact WHERE AccountId =: a.Id];
		    System.debug(conList);
        }
    }
    
    public static void printDetails() {
           List<C__c> cList = [Select Name, A__r.Name, B__r.Name FROM C__c Where Name = 'John'];
        System.debug(cList);
    } 
    
    public static void printAcc() {
        List<Account> accountList = [SELECT Name, AccountNumber, (SELECT Name, Email FROM Contacts WHERE Name Like '%John%') FROM Account];
        System.debug(accountList);
    }
    
    public static void printOpportunity() {
        List<Account> accountList = [SELECT Name, (SELECT Name FROM Opportunities where StageName='Closed Won') FROM Account];
        System.debug(accountList);
    }
    
    public static void parentDetails() {
        List<A__c> alist = [SELECT Name, (SELECT Name FROM C__r WHERE Name='John') FROM A__c];
        System.debug(alist);	
    }
}