force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student__c/fields/Roll_Number__c.field-meta.xml
<CustomField>
    <fullName>Roll_Number__c</fullName>
    <label>Roll Number</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TestStudentInformation.cls
@isTest
public class TestStudentInformation {
	@testSetup
    static void setup() {
       List<Student__c> studentList = new List<Student__c>();
        for(Integer i = 0; i < 5; i++) {
            studentList.add(new Student__c(	Roll_Number__c = 22+i, Name = 'Rohan', 	Gender__c = 'Male'));
        }
        insert studentList;
    }
    
    @isTest
    public static void testStudent() {
        Test.startTest();
			Student__c studentObj = new Student__c();
        	ApexPages.StandardController sc = new ApexPages.StandardController(studentObj);
        	StudentInformation studentInfoObj = new StudentInformation(sc);
        	studentInfoObj.getLanguageChoosen();
        	studentInfoObj.save();
        Test.stopTest();
        System.assert(studentInfoObj.save() != null);
        System.assert(studentInfoObj.langList != null);
    }
}